providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = []

[phases.install]
cmds = []

[phases.build]
cmds = ["npm install --prefer-offline=false --cache /tmp/.npm --no-audit --no-fund", "npm run build"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/.npm"
